# name: On New Tag Publish

# on:
#     push:
#         tags:
#             - 'v*'

# permissions:
#     contents: read
#     pages: write
#     id-token: write

# jobs:
#     call-publish-windows:
#         uses: ./.github/workflows/publish-windows.yml
#         with:
#             tag: ${{ github.ref_name }}
#         secrets:
#             RELEASE: ${{ secrets.RELEASE }}

#     # call-publish-linux:
#     #     uses: ./.github/workflows/publish-linux.yml
#     #     with:
#     #         tag: ${{ github.ref_name }}
#     #     secrets:
#     #         RELEASE: ${{ secrets.RELEASE }}

#     # call-publish-mac:
#     #     uses: ./.github/workflows/publish-mac.yml
#     #     with:
#     #         tag: ${{ github.ref_name }}
#     #     secrets:
#     #         RELEASE: ${{ secrets.RELEASE }}

#     # call-publish-website:
#     #     uses: ./.github/workflows/publish-website.yml
#     #     with:
#     #         tag: ${{ github.ref_name }}
#     #     secrets:
#     #         RELEASE: ${{ secrets.RELEASE }}
